name: Deploy django on ec2

on:
  push:
    branches:
      - release
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Convert SSH Private Key to PEM
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key_ssh.pem
          chmod 600 private_key_ssh.pem
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

      - name: Add EC2 IP to Known Hosts
        run: |
          echo "Adding EC2 IP to known hosts..."
          ssh-keyscan -H $EC2_PUBLIC_IP >> $HOME/.ssh/known_hosts
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

      - name: SSH into EC2 Instance
        run: |
          echo "Connecting to the EC2 instance..."
          ssh -i ./private_key_ssh.pem ubuntu@${EC2_PUBLIC_IP} << EOF
            echo "Entering the project directory..."
            cd /home/ubuntu/deployment
            ls
            echo "Pulling the latest changes from the 'release' branch..."
            git pull origin release 
            echo "Stopping and removing Docker containers..."
            sudo docker compose down
            echo "Building and starting Docker containers..."
            sudo docker compose up --build -d
          EOF
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}